# Fly.io configuration for Café Direct ordering system
app = 'cafe-direct-ordering'
primary_region = 'sjc'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = '15s'
  timeout = '2s'
  grace_period = '5s'
  method = 'GET'
  path = '/api/health'

[vm]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/dist/public'
  url_prefix = '/static/'